
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const LOGIN_ACTION_ERROR = 'LOGIN_ACTION_ERROR';

export const SIGNUP_ACTION = 'SINGUP_ACTION';
export const SINGUP_ACTION_SUCCESS = 'SINGUP_ACTION_SUCCESS';
export const SINGUP_ACTION_ERROR = 'SINGUP_ACTION_ERROR';